### ISSUE TITLE
Issue with docker file

### ISSUE THREAD

**Issue by jcgrenier** [jhawe/rpeer#1]
Hello @jhawe ,

Thanks for putting this program into a Docker container! We really struggled installing it on more recent machines. I'm having trouble pulling your docker container using singularity on our system. Here's the error I'm getting : 

FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack layer: read next entry: archive/tar: invalid tar header

Could you help me?
Thanks a lot for your help!

**Comment by jhawe** [comment]
hi,

this is weird, it should work 'as is' from the docker hub. have your tried building the image from scratch, i.e. using the dockerfile? do you get the same error? it might be related to your build system as well, but i'm not sure, since i think the error you're getting rather indicates an issue with the image itself.

In case the steps above do not work, you could also get the exported 'sif' file (singularity image) from this link (I just uploaded it): https://drive.google.com/file/d/1UJakv7VuoTDHjcsa5o5XvTIQVVdDHgBG/view?usp=sharing

(file is couple 100MB in size)

I can run this image without issues on my system, e.g.:

```
~: singularity run peer_data.sif R
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(peer)
>
```

hope that helps!

> EDIT: just a thought: depending on what you need to do, you might want to consider using simple PCA or MOFA instead of PEER.

**Comment by jcgrenier** [comment]
Hello @jhawe,

The sif file seems to work! Thanks a lot! I don't know what happened during the compilation. I'll give a look at MOFA. A PCA was not good enough for my project! 
Best,

JC
